all:	genTests.exe
	
genTests.exe:	genTests.cpp
	g++ -o genTests.exe genTests.cpp

clean:
	rm genTests.exe
	rm UDgraphRand100out/t*
	rm UDgraphRand10out/t*
	rm DgraphRand100out/t*
	rm DgraphRand10out/t*
	rm AllSameout/t*
