<label for="expected">
  Expected Range *
</label>
<div>
  <div id="expected" class="numeric interval">
    <label for="expected-min">Min</label>
    <div><input name="expected[min]" id="expected-min" value="" class="tst-expected-min numeric"></div>
    <label for="expected-max">Max</label>
    <div><input name="expected[max]" id="expected-max" value="" class="tst-expected-max numeric"></div>
  </div>
</div>