<label for="quantity">
  {{measure_label}}
</label>
<div>
  <select name="quantity" id="quantity" class="tst-quantity">
    <option value="" selected>
      Select
    </option>
    <option value="temperature">
      Temperature
    </option>
    <option value="pressure">
      Pressure
    </option>
    <option value="flow">
      Flow Rate
    </option>
    <option value="humidity">
      Relative Humidity
    </option>
  </select>
</div>