all: arith1 arith2

prob8: arith2_prob8.c
	gcc -g -Wall -Wextra -o prob8 arith2_prob8.c

prob4: arith1_prob4.c
	gcc -g -Wall -Wextra -o prob4 arith1_prob4.c

arith1: arith1.c
	gcc -g -Wall -Wextra -o arith1 arith1.c

arith2: arith2.c
	gcc -g -Wall -Wextra -o arith2 arith2.c

clean:
	rm arith1 arith2 prob4 prob8
